#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication -o ideasUnvToFoam pipeWithDuct.unv

runApplication -o splitMeshRegions -cellZones -overwrite

paraFoam -region duct -touch
paraFoam -region pipe -touch

runApplication $(getApplication)

#------------------------------------------------------------------------------
